[package]
name = "fsse"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

[dependencies]
rand = { version = "*", features = [ "i128_support" ] }
siphasher = "*"
itertools = "*"
